source loadDesignTech.tcl
source initialFloorplan.tcl
source pin_placement.tcl
source placement.tcl
source addFiller.tcl
source clock.tcl
source route.tcl
source reportDesign.tcl
source outputGen.tcl
